primeironum =float(input("primeiro num "))
segumdonum =float(input("segumdo num "))
terceironum =float(input("terceiro num "))
quartonum =float(input("quarto num "))
quintonum =float(input("quinto num "))